language: python
cache: pip
sudo: false
matrix:
  include:
  - env: TOXENV=py27-django15
    python: 2.7
  - env: TOXENV=py27-django16
    python: 2.7
  - env: TOXENV=py27-django17
    python: 2.7
  - env: TOXENV=py33-django17
    python: 3.3
  - env: TOXENV=py33-django18
    python: 3.3
  - env: TOXENV=py34-django18
    python: 3.4
  - env: TOXENV=py34-django19
    python: 3.4
  - env: TOXENV=py34-django110
    python: 3.4
  - env: TOXENV=py35-django110
    python: 3.5
install:
  - pip install tox
script:
- tox
